# This file provides instructions for packaging.

`MooseX-Interface`
	perl_version_from m`MooseX::Interface`;
	version_from      m`MooseX::Interface`;
	readme_from       m`MooseX::Interface`;
	requires          p`B::Hooks::EndOfScope`;
	requires          p`B::Hooks::Parser`;
	requires          p`Class::Load`;
	requires          p`Contextual::Return`;
	requires          p`Moose 2.00`;
	requires          p`namespace::clean 0.19`;
	test_requires     p`Test::More 0.61`.

